version: '3.8'

services:

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: dk5f95/order-service
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - .:/app
    restart: on-failure
    ports:
      - 8000:8000

    networks:
      - strategymanager_strategy-network


  order-service-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: dk5f95/order-service-worker
    command: /start-celeryworker
    volumes:
      - .:/app
#    depends_on:
#      - rabbitmq
    networks:
      - strategymanager_strategy-network

  order-service-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    image: dk5f95/order-service-celery-beat
    command: /start-celerybeat
    depends_on:
      - order-service-worker
#      - rabbitmq
    networks:
      - strategymanager_strategy-network

networks:
  strategymanager_strategy-network:
    external: true